sudo: false
cache: pip
language: python

branches:
  only:
    - master
    - development

install:
  - python setup.py install
  - pip install nose coverage mypy flake8 coveralls

script:
  - nosetests --config="" --cover-package=simsusy --with-coverage
  - mypy --ignore-missing-imports --follow-imports=silent --no-strict-optional .
  - flake8 --max-line-length=120 .
  - coveralls

